language: rust
cache: cargo

sudo: required

rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
env:
  global:
  - RUST_BACKTRACE=1
  - RUSTFLAGS="-C link-dead-code"
  - CARGO_MAKE_RUN_CODECOV="true"
script:
  - cargo install --debug cargo-make
  - cargo build --verbose
  - docker-compose up -d
  - timeout 60 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:8081/subjects)" != "200" ]]; do sleep 3; done' || false
  - cargo test --verbose --all-features -- --test-threads=1
  - cargo make --makefile make.toml ci-flow