language: rust
cache: cargo

sudo: required

rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
env:
  global:
  - RUST_BACKTRACE=1
  - RUSTFLAGS="-C link-dead-code"
  - CARGO_MAKE_RUN_CODECOV="true"
script:
  - cargo install --debug cargo-make
  - cargo build --verbose
  - docker-compose up -d
  - ./check_test_app_done.sh
  - ./prepare_integration_test.sh
  - cargo test --verbose --all-features -- --test-threads=1
  - cargo make --makefile make.toml ci-flow