[tasks.test-verbose]
command = "cargo"
args = ["test", "--verbose", "--features", "avro", "--", "--test-threads=1"]

[tasks.test]
command = "cargo"
args = ["test", "--features", "avro", "--", "--test-threads=1"]