[tasks.test-verbose]
command = "cargo"
args = ["test", "--verbose", "--all-features", "--", "--test-threads=1"]

[tasks.test]
command = "cargo"
args = ["test", "--all-features", "--", "--test-threads=1"]