@startuml
title Consumer activity flow

(*) -> "Create decoder"
(*) -> "Create Kafka consumer"
"Create Kafka consumer" -> "Get a Kafka message"
"Get a Kafka message" -> "Either Key or Value"

if "Magic byte in place?" then
  -->[yes] "Get id"
  if "Id in cache?" then
  -> [yes] "Apply schema to bytes"
  else
  --> [no] "Get schema and add to cache, might\nneed to resolve references"
  "Get schema and add to cache, might\nneed to resolve references" --> "Apply schema to bytes"
  endif
else
  -->[no] if "Message  empty?" then
    --> [yes] "Null"
  else
    -->[no] "Bytes"
  endif
endif

"Create decoder" --> "Get schema and add to cache, might\nneed to resolve references"
"Create decoder" --> "Get id"

"Apply schema to bytes" -> "Serialised data"
"Serialised data" -> "Do something with the Value"
"Bytes" --> "Do something with the Value"
"Null" --> "Do something with the Value"
@enduml