@startuml

(*) -> "Create encoder"
(*) --> "Create Kafka client"
(*) --> "Create SubjectNameStrategy"
(*) -l-> "Depending on encoder\nhave data with correct type"
"Create encoder" -> "Encode with encoder"
"Create SubjectNameStrategy" --> "Encode with encoder"
"Depending on encoder\nhave data with correct type" --> "Encode with encoder"

if "Subject in cache?" then
  -->[yes] "Use schema and id to transform to bytes"
else
  -r-> [no] "Get or register schema\nand possible references"
  "Get or register schema\nand possible references" --> "Use schema and id to transform to bytes"
endif

"Use schema and id to transform to bytes" -r-> "Send as key or value"
"Create Kafka client" --> "Send as key or value"
@enduml